name: Daily Game Layout Update

on:
  schedule:
    - cron: '0 11 * * *'  # 11:00 UTC = 7:00 AM EDT
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with PAT
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests ics pytz openpyxl

    - name: Run layout generator
      run: python "Weekly Visual Rec Schedule.py"

    - name: Commit and push updated HTML
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add index.html
        git diff --cached --quiet || git commit -m "🔄 Daily update: game layout"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        git push origin main

    - name: Show Git identity
      run: git config --list
