name: Daily Game Layout Update

on:
  schedule:
    - cron: '0 11 * * *'  # 11:00 UTC = 7:00 AM EDT
  workflow_dispatch:      # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests ics pytz openpyxl

    - name: Run layout generator
      run: python "Weekly Visual Rec Schedule.py"

    - name: Commit and push updated HTML
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add *.html
        git commit -m "🔄 Daily update: game layout"
        git push
